site_name: Json Model
pages:
  - Home: index.md
  - jsonModel Class: jsonmodel.md
  - Reference: reference.md
  - Extensions: extensions.md
  - Roadmap: roadmap.md
  - Test: test.md
markdown_extensions: [ footnotes, smarty, abbr ]