''' A Collection of Methods for Validating JSON Structured Data '''
__author__ = 'rcj1492'
__created__ = '2015.12'
__version__ = '3.1'
__license__ = 'MIT'
__module__ = 'jsonmodel'
__email__ = 'support@collectiveacuity.com'
__url__ = 'https://github.com/collectiveacuity/jsonModel'
__description__ = 'A Collection of Methods for Validating JSON Structured Data'